### ISSUE TITLE
Only MenuBar

### ISSUE THREAD

**Issue by Angelk90** [okwasniewski/react-native-menubar-extra#14]
Hi @okwasniewski , It would be possible to have only the MenuBar.

That is, when the app is started, the screen with the word "Hello!" does not appear.

**Comment by okwasniewski** [comment]
Hey @Angelk90, 

It's possible! However, it's not that simple. You need to take a more brownfield approach to achieve this. 

Here you have a tutorial from @ospfranco that explains this pretty well: 
https://ospfranco.com/post/2020/05/23/how-to-make-a-react-native-menu-bar-app-for-mac-os/

The thing that you need to modify is instead of setting `popover.contentViewController = rootViewController` you need to store `rootViewController` as a non-retained property on AppDelegate so it's kept alive. 

I will create a blog post soon on how to achieve this with this lib 👍🏻

**Comment by okwasniewski** [comment]
Hey,

I've released blog post on this topic recently: https://www.oskarkwasniewski.dev/blog/create-react-native-macos-menubar-app
